---
title: "Figure 6"
output:
 html_document:
    toc: true
    toc_float: true
    code_folding: hide
    theme: flatly
date: "2026-09-21"
---

# Setup
```{r setup, include=FALSE}
# Set printing source code
knitr::opts_chunk$set(echo = TRUE)

# Load packages
# CRAN packages
library(tidyverse)
library(patchwork)
library(gridExtra)
library(rstatix)
library(purrr)
library(here)
library(matrixStats)
library(ggpubr)
library(stats)

# Bioconductor packages
library(GenomicRanges)
library(GenomicFeatures)
library(PCAtools)

# Set correct select function
select = dplyr::select
count = dplyr::count

# Define tissue colors
types = c("Stipe","Lamella","Spore","control")
colors = c("#96C176FF","#CF9DDBFF","#4472C4FF","#000000FF")
types = c("Stipe","Lamella","Spore","control","stipe","lamella","spore") # Catch lowercase tissues
colors = c("#96C176FF","#CF9DDBFF","#4472C4FF","#000000FF","#96C176FF","#CF9DDBFF","#4472C4FF")
names(colors) = types

# Define genomic context colors
annotationColors = c("mRNA" = "#4472C4","TE" = "#C00000","Both" = "#9D475B","intergenic" = "#AFABAB")

# Define methylation level colors (< 0.05, 0.05 - 0.30, 0.30 - 0.75, 0.75 - 0.90, > 0.90)
methylationLevelColors = my_colors <- c(
  "Nothing"   = "#4575B4",
  "Low"  = "#91BFDB",
  "Medium"  = "#E0F3F8",
  "High"  = "#FEE090",
  "All" = "#D73027"
)

```

# Annotation

## TE reference
```{r, message=FALSE}
# Define GFF3 columns
gff3Colnames =c("seqid", "source",
                "type","start",
                "end", "score",
                "strand","phase",
                "attributes")

  # Load information about TE classes, included in repository
  TE.classes = read_csv(file = here("annotation","Repeat.classes.csv")) %>%
    rename(Name = "TEfamily") %>% 
    rename("Superfamily / Notes" = "Notes") #columns renamed for downstream use

  # Define TE file location, included in repository
  TEFile <- here("annotation","Maror2.repeatmasker.rmlib2.3.gff")

  # Read in TE dataframe from gff file
  TEdf =    read_tsv(file = TEFile, col_names = gff3Colnames,comment = "#") %>% separate(attributes, into = c("ID","target"), sep = ";") %>%
    mutate(ID = as.numeric(gsub("ID=","",ID))) %>%
    separate(target, into = c("Target","motif",
                              "motifStart","motifStop"),
             sep = " ") %>%
    mutate(motif = gsub("\"","",motif))%>%
    mutate(motif = gsub("Motif:","",motif))  %>%
    select(seqid,start,end,score,
           strand, ID,motif,
           motifStart,motifStop) %>%
    rename(ID = "TEID") %>%
    mutate(TE_ID2 = 1:n()) %>%
    mutate(motifStart = as.numeric(gsub(" ","",motifStart))) %>%
    mutate(motifStop = as.numeric(gsub(" ","",motifStop))) %>%
    dplyr::rename(TEclass = "motif") %>%
    mutate(TEclass = gsub(" ","",TEclass)) %>%
    mutate(TEclass = gsub("Maror","",TEclass)) 

 
  # Generate GRanges of TE file
  TEs = makeGRangesFromDataFrame(TEdf,
                                 seqnames.field = "seqid", 
                                 start.field = "start", 
                                 end.field = "end",
                                 strand.field = "strand",
                                 keep.extra.columns = TRUE)
  

# Merge TE classes with dataframe to add annotation and remove other repeat annotations
# From 13309 to 8893 repeats
TEdf%>%
  separate(TEclass, into = c("TEfamily","nr"), sep = "-",remove = FALSE) %>%
  inner_join(TE.classes)->
  TEdf

```

## Gene reference 
```{r, message=FALSE}

gtfFile = here("annotation","GCF_018924745.1_UU_Maror_2_genomic.gff")	# Included in repository
txdb <- makeTxDbFromGFF(file=gtfFile, dataSource="ensemblgenomes",format = "gff3")

# define GFF3 columns
gff3Colnames =c("seqid", "source",
                "type","start",
                "end", "score",
                "strand","phase",
                "attributes")
  # Read in the gff file
  annotation.df =    read_tsv(file = gtfFile, col_names = gff3Colnames,comment = "#") 

# Keep only mRNA annotations
 annotation.df %>% filter(type =="mRNA") %>%
   group_by(seqid,start,end, strand) %>%
   slice_head(n = 1) %>% # Remove multiple mRNA annotations on the same genomic region
   ungroup() %>%
   separate_longer_delim(attributes, delim = ";") ->
   test
  # Keep only relevant attributes and give them separate columns
  # Drop any unused columns
  test %>% select(seqid,start,end,strand,attributes) %>%
   separate(attributes, into = c("key","value"), sep = "=") %>%
   filter(key %in% c("Name","locus_tag","product")) %>%
   pivot_wider(values_from = "value",names_from = "key") -> 
   annotation.mRNA.df

# Add tx_id column
annotation.mRNA.df %>% select(seqid,start,end, strand,Name,locus_tag,product) %>%
  mutate(tx_id = 1:n()) -> 
  annotation.mRNA.df

# Create GRanges object
mRNAs = makeGRangesFromDataFrame(annotation.mRNA.df,
                                 seqnames.field = "seqid", 
                                 start.field = "start", 
                                 end.field = "end",
                                 strand.field = "strand",
                                 keep.extra.columns = TRUE)
  

```

## Relationship between XM and XP IDs
```{r, inlcude false  }
# Add XM and XP IDs
gene2ProteinFile = here("annotation","gene2protein_relationship.csv")

relationship_df = read_csv(gene2ProteinFile)

relationship_df %>% mutate(Name = XM_ID) -> relationship_df
annotation.mRNA.df = inner_join(annotation.mRNA.df,relationship_df , by = "Name")
```

# Samples 
```{r, message=FALSE}

# Read and organize sample data
samples.ring.methyl.df = read_csv(file = here("data","meDNA","meDNA.metaData.csv"))

samples.ring.methyl.df %>% arrange(Tissue,Location,Replicate) -> 
  samples.ring.methyl.df

```

# Read in data
```{r, message=FALSE}
#TODO: Insert DOI
# Data can be obtained from ###INSERT DOI#####
meData_path <- here("data", "meDNA", "methylationData.samples.QC.csv.gz")

# Read in the data, read_csv automatically handles the decompression
# Data consists of every position of every sample that is considered in the final dataset. 
methylationData.3.QC <- read_csv(meData_path)

```

# Perform PCA to test relationship
```{r, message=FALSE}
methylationData.3.QC %>% 
  mutate(CpG = paste(seqid, start, sep=":")) %>%
  select(CpG, Sample, Tissue, Location, Replicate2, percent) %>%
  pivot_wider(values_from = "percent", names_from = "CpG") -> input_pca

input_pca %>%
  select(Sample, Tissue, Location, Replicate2) -> meta

#convert to matrix
meth_matrix <- as.matrix(select(input_pca, -Sample, -Tissue, -Location, -Replicate2))
rownames(meth_matrix) <- input_pca$Sample

# transform data
beta_mat <- meth_matrix / 100
beta_mat[beta_mat <= 0] = 0.001
beta_mat[beta_mat >= 1] <- 0.999
m_mat <- log2(beta_mat / (1 - beta_mat))

#calculate variance and keep most variable sites
cpg_variances <- colVars(m_mat)
top_cpgs <- head(order(cpg_variances, decreasing = TRUE), 50000)
filtered_mat <- m_mat[, top_cpgs]

#pca 
pca_res <- prcomp(filtered_mat, center = TRUE, scale. = FALSE)
pca_scores <- as.data.frame(pca_res$x)
pca_scores$Sample <- rownames(pca_scores)

#carculate variance explained
var_explained <- (pca_res$sdev^2) / sum(pca_res$sdev^2) * 100
pc1_lab <- paste0("PC1 (", round(var_explained[1], 1), "% variance)")
pc2_lab <- paste0("PC2 (", round(var_explained[2], 1), "% variance)")

plot_data <- left_join(meta, pca_scores, by = "Sample")

ggplot(plot_data, aes(x = PC1, y = PC2, color = Tissue, shape = Location)) +
  geom_point(size = 3, alpha = 0.85) +
  labs(
    x = pc1_lab,
    y = pc2_lab,
    title = "PCA of top 50,000 variable CpGs",
    color = "Tissue",
    shape = "Location") +
    theme_classic(base_size = 10) + 
    theme(plot.title = element_text(hjust = 0.5, face = "bold")) -> PCA_plot

ggsave(here("figures", "Figure6", "Fig6A.pdf"), width = 6, height = 5, PCA_plot)


# distribution of types of sites in the selected CpGs
top_CpG_df <- methylationData.3.QC %>%
  select(seqid, start, location, Name, TE_ID2, TEclass, percent, Sample, Tissue) %>%
  mutate(CpG = paste(seqid, start, sep=":")) %>%
  filter(CpG %in% colnames(m_mat)[top_cpgs]) %>%
  group_by(CpG, Tissue, location) %>%
  summarize(mean_methylation = mean(percent), .groups = "drop") %>%
  pivot_wider(names_from = Tissue, values_from = mean_methylation) %>%
  mutate(lamella_stipe_difference = stipe - lamella) %>%
  mutate(lamella_spore_difference = spore - lamella) %>%
  mutate(stipe_spore_difference = stipe - spore)

top_CpG_count <- top_CpG_df %>% count(location)

# explore loadings
loadings <- as.data.frame(pca_res$rotation)
top_CpG_df <- loadings %>%
  rownames_to_column("CpG") %>%
  select(CpG, PC1, PC2) %>%
  right_join(top_CpG_df, by = "CpG")

# add loadings to the CpG df

top_PC1_df <- data.frame(CpG = rownames(loadings)[order(abs(loadings$PC1), decreasing = TRUE)[1:500]])
top_PC2_df <- data.frame(CpG = rownames(loadings)[order(abs(loadings$PC2), decreasing = TRUE)[1:500]])

top_PC1_df <- top_CpG_df %>%
  right_join(top_PC1_df, by = "CpG")

top_PC2_df <- top_CpG_df %>%
  right_join(top_PC2_df, by = "CpG")

# count hits 
top_PC1_count <- top_PC1_df %>% count(location)
top_PC2_count <- top_PC2_df %>% count(location)

# test if there is significant difference between groups
mat_1 <- rbind(total = top_CpG_count$n - top_PC1_count$n, PC1_count = top_PC1_count$n)
mat_1 <- t(mat_1)
chi_mat_1 <- chisq.test(mat_1)
chi_mat_1
chi_mat_1$residuals


mat_2 <- rbind(total = top_CpG_count$n - top_PC1_count$n, PC2_count = top_PC2_count$n)
mat_2 <- t(mat_2)
chi_mat_2 <- chisq.test(mat_2)
chi_mat_2
chi_mat_2$residuals

# plot relationship of PCs with changes in methylation between tissues
# PC1
ggplot(top_CpG_df, aes(x = lamella_stipe_difference, y = PC1)) + geom_point()
ggplot(top_CpG_df, aes(x = lamella_spore_difference, y = PC1)) + geom_point()
ggplot(top_CpG_df, aes(x = stipe_spore_difference, y = PC1)) + geom_point()

 # PC2
ggplot(top_CpG_df, aes(x = lamella_stipe_difference, y = PC2)) + geom_point()
ggplot(top_CpG_df, aes(x = lamella_spore_difference, y = PC2)) + geom_point()
ggplot(top_CpG_df, aes(x = stipe_spore_difference, y = PC2)) + geom_point()

# These plots showed that PC1 is driven by tissues, but not PC2

```

# Correlate samples to see inheritance

```{r}

# Select data to use and split into list
methylationData.3.QC %>%
  mutate(individual = paste(Location, Replicate2, sep = "_")) %>%
  mutate(cpg_id = paste(seqid, start, sep = ":")) %>%
  select(Sample, cpg_id, percent, Location, Tissue, Replicate2, individual, location) %>%
  split(.$Sample) -> sample_data_list

percentage_same_methylation <- function(
    sample_1,
    sample_2,
    data_list = sample_data_list,
    max_absolute_difference = 10.1,
    group_by_location = FALSE) {
    
    # transform the data into a usable comparison
    data_sample_1 <- data_list[[sample_1]]

    data_sample_2 <- data_list[[sample_2]]

    #calculate percent similarity 
    data_sample_1 %>%
      inner_join(data_sample_2, by = "cpg_id", suffix = c("_1", "_2")) %>%
      filter(!is.na(percent_1) & !is.na(percent_2)) -> joined_data

    if(group_by_location){
      joined_data <- joined_data %>% group_by(location_1)
    } 
    result <- joined_data %>% summarize(
      individual_1 = individual_1[1],
      individual_2 = individual_2[1],
      same_individual = individual_1[1] == individual_2[1],
      same_location = Location_1[1] == Location_2[1],
      tissue_1 = Tissue_1[1],
      tissue_2 = Tissue_2[1],
      total_shared_sites = n(),
      mean_difference = mean(abs(percent_1 - percent_2)),
      sites_within_pct = sum(abs(percent_1 - percent_2) <= max_absolute_difference),
      pct_overlap = (sites_within_pct / total_shared_sites),
      pearson = cor(percent_1, percent_2, method = "pearson", use = "complete.obs"),
      spearman = cor(percent_1, percent_2, method = "spearman", use = "complete.obs"),
      .groups = "drop")
    return(result)
}

# create a comparison of each 
methylationData.3.QC %>%
  select(Sample, Tissue) %>%
  distinct() -> samples_table 

samples_table %>%
  filter(Tissue == "lamella") %>%
  select(Sample_1 = Sample) -> lamella_samples

samples_table %>%
  filter(Tissue %in% c("spore", "stipe")) %>%
  select(Sample_2 = Sample, Tissue_2 = Tissue) -> other_samples

pairs <- cross_join(lamella_samples, other_samples)

# run the function
pairs %>%
  mutate(results = pmap(list(Sample_1, Sample_2), percentage_same_methylation, .progress = TRUE)) %>%
  pull(results) %>%
  list_rbind() -> all_results


# Run version where methylation maintenance is calculated by category
pairs %>%
  mutate(results = pmap(list(Sample_1, Sample_2), percentage_same_methylation, group_by_location = TRUE, .progress = TRUE)) %>%
  pull(results) %>%
  list_rbind() -> all_results_grouped_location

# plot the overlap
all_results %>%
  filter(same_location == TRUE) %>%
  mutate(same_individual = factor(same_individual, levels = c(TRUE, FALSE))) %>%
  mutate(same_location = factor(same_location, levels = c(TRUE, FALSE))) %>%
  ggplot(aes(x = tissue_2, y = pct_overlap, fill = same_individual)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6, position = position_dodge(0.8)) +
  geom_point(aes(shape = same_location, group = same_individual), color = "grey30", position = position_jitterdodge(jitter.width = 0.35, dodge.width = 0.8), size = 2, alpha = 2) +
  stat_compare_means(aes(group = same_individual), method = "wilcox.test", label = "p.format", label.y = max(all_results$pct_overlap, na.rm = TRUE) + 0.02, hide.ns = FALSE, size = 4) +
  labs(x = "", y = "Fraction overlap within 10%") +
  scale_x_discrete(labels = c("spore" = "Lamella vs spore", "stipe" = "Lamella vs stipe")) +
  scale_shape_discrete(name = "Location", labels = c("TRUE" = "Same location", "FALSE" = "Different location")) +
  scale_fill_discrete(name = "Individual", labels = c("TRUE" = "Same individual", "FALSE" = "Different individual")) +
  theme_classic(base_size = 14) -> overlap_boxplot_no_different_location

# plot overlap without different locations
all_results %>%
  filter(same_location == TRUE) %>%
  mutate(same_individual = factor(same_individual, levels = c(TRUE, FALSE))) %>%
  mutate(same_location = factor(same_location, levels = c(TRUE, FALSE))) %>%
  ggplot(aes(x = tissue_2, y = pct_overlap, fill = same_individual)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6, position = position_dodge(0.8)) +
  geom_point(aes(shape = same_location, group = same_individual), color = "grey30", position = position_jitterdodge(jitter.width = 0.35, dodge.width = 0.8), size = 2, alpha = 2) +
  stat_compare_means(aes(group = same_individual), method = "wilcox.test", label = "p.format", label.y = max(all_results$pct_overlap, na.rm = TRUE) + 0.02, hide.ns = FALSE, size = 4) +
  labs(x = "", y = "Fraction overlap within 10%") +
  scale_x_discrete(labels = c("spore" = "Lamella vs spore", "stipe" = "Lamella vs stipe")) +
  scale_shape_discrete(name = "Location", labels = c("TRUE" = "Same location", "FALSE" = "Different location")) +
  scale_fill_discrete(name = "Individual", labels = c("TRUE" = "Same individual", "FALSE" = "Different individual")) +
  theme_classic(base_size = 14) -> overlap_boxplot_no_different_location

ggsave(here("figures", "Figure6", "Fig6B.pdf"), width = 7, height = 5, overlap_boxplot)
ggsave(here("figures", "SuppFigures", "supplemental_figure_4A.pdf"), width = 7, height = 5, overlap_boxplot_no_different_location)

all_results_grouped_location %>%
  mutate(same_individual = factor(same_individual, levels = c(TRUE, FALSE))) %>%
  mutate(same_location = factor(same_location, levels = c(TRUE, FALSE))) %>%
  ggplot(aes(x = tissue_2, y = pct_overlap, fill = same_individual)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6, position = position_dodge(0.8)) +
  geom_point(aes(shape = same_location, group = same_individual), color = "grey30", position = position_jitterdodge(jitter.width = 0.35, dodge.width = 0.8), size = 2, alpha = 2) +
  stat_compare_means(aes(group = same_individual), method = "wilcox.test", label = "p.format", label.y = max(all_results$pct_overlap, na.rm = TRUE) + 0.02, hide.ns = FALSE, size = 3.5) +
  facet_wrap(~ location_1) +
  labs(x = "", y = "Fraction overlap within 10%") +
  scale_x_discrete(labels = c("spore" = "Lamella\nvs spore", "stipe" = "Lamella\nvs stipe")) +
  scale_shape_discrete(name = "Location", labels = c("TRUE" = "Same location", "FALSE" = "Different location")) +
  scale_fill_discrete(name = "Individual", labels = c("TRUE" = "Same individual", "FALSE" = "Different individual")) + 
  theme_classic(base_size = 14) -> overlap_boxplot_grouped

ggsave(here("figures", "SuppFigures", "supplemental_figure_4B.pdf"), width = 12, height = 5, overlap_boxplot_grouped)

#unused plots
ggplot(all_results, aes(x = tissue_2, y = mean_difference, fill = same_individual)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6, position = position_dodge(0.8)) +
  geom_point(aes(color = same_individual), position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8), size = 2, alpha = 0.8) +
  stat_compare_means(aes(group = same_individual), method = "wilcox.test", label = "p.format", label.y = max(all_results$pct_overlap, na.rm = TRUE) + 0.02, hide.ns = FALSE) +
  facet_wrap(~ location_1) +
  labs(x = "Lamellae vs", y = "Mean difference per position", title = "Mean difference in CpG methylation within and between mushrooms per genomic context") +
  theme_classic(base_size = 12) -> mean_difference_boxplot



#plotting spearman and pearson

ggplot(all_results, aes(x = tissue_2, y = spearman, fill = same_individual)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6, position = position_dodge(0.8)) +
  geom_point(aes(color = same_individual), position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8), size = 2, alpha = 0.8) +
  stat_compare_means(aes(group = same_individual), method = "wilcox.test", label = "p.format", label.y = max(all_results$pct_overlap, na.rm = TRUE) + 0.001, hide.ns = FALSE) +
  facet_wrap(~ location_1) +
  labs(x = "Lamellae vs", y = "Spearman correlation") +
  theme_classic(base_size = 12) -> spearman_boxplot

#ggsave(here("figures", "Figure1", "spearman_correlation.png"), spearman_boxplot)

ggplot(all_results, aes(x = tissue_2, y = pearson, fill = same_individual)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6, position = position_dodge(0.8)) +
  geom_point(aes(color = same_individual), position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8), size = 2, alpha = 0.8) +
  stat_compare_means(aes(group = same_individual), method = "wilcox.test", label = "p.format", label.y = max(all_results$pct_overlap, na.rm = TRUE) + 0.001, hide.ns = FALSE) +
  facet_wrap(~ location_1) +
  labs(x = "Lamellae vs", y = "Pearson correlation") +
  theme_classic(base_size = 12) -> pearson_boxplot



```