---
title: "Methylation pattern"
output:
 html_document:
    toc: true
    toc_float: true
    code_folding: hide
    df_print: paged  # This makes all dataframes scrollable/paginated
date: "2024-09-11"
---

## setup
```{r setup, include=FALSE}
# Set printing source code
knitr::opts_chunk$set(echo = TRUE)

# Load packages
# CRAN packages
library(tidyverse)
library(here)
library(ggrepel)
library(patchwork)
library(openxlsx)

#Bioconductor packages
library(clusterProfiler)
library(GO.db)
library(GenomicRanges)
library(GenomicFeatures)
library(DESeq2)

# Set correct select function
select = dplyr::select

# Define tissue colors
types = c("Stipe","Lamella","Spore","control")
colors = c("#96C176FF","#CF9DDBFF","#4472C4FF","#000000FF")
types = c("Stipe","Lamella","Spore","control","stipe","lamella","spore") # Catch lowercase tissues
colors = c("#96C176FF","#CF9DDBFF","#4472C4FF","#000000FF","#96C176FF","#CF9DDBFF","#4472C4FF")
names(colors) = types

# Define genomic context colors
annotationColors = c("mRNA" = "#4472C4","TE" = "#C00000","Both" = "#9D475B","intergenic" = "#AFABAB")

# Define methylation level colors (< 0.05, 0.05 - 0.30, 0.30 - 0.75, 0.75 - 0.90, > 0.90)
methylationLevelColors = my_colors <- c(
  "Nothing"   = "#4575B4",
  "Low"  = "#91BFDB",
  "Medium"  = "#E0F3F8",
  "High"  = "#FEE090",
  "All" = "#D73027"
)
```

## Data from Nextflow

```{r}
# Set data dir
dataDir = here("data", "RNA", "repeats", "salmon")
```

## Samples 
```{r}
# Load in samples

samples.ring.RNA.df = read_csv(file = here("data","RNA","RNA.samples.csv"))
samples.ring.RNA.df %>%
  mutate(Sample = sample) %>%
  mutate(sample = gsub("NE","northeast_",sample)) %>%
  mutate(sample = gsub("NW","northwest_",sample)) %>%
  mutate(sample = gsub("N","north_",sample)) %>%
  mutate(sample = gsub("E","east_",sample)) %>%
  mutate(sample = gsub("W","west_",sample)) %>%
  mutate(sample = gsub("SP","_spore",sample)) %>%
  mutate(sample = gsub("S","_stipe",sample)) %>%
  mutate(sample = gsub("L","_lamella",sample)) ->
  samples.ring.RNA.df
samples.ring.RNA.df %>%
  tidyr::separate_wider_delim(col = sample,
                              names = 
                    c("Location","Replicate",
                           "Tissue"),
           delim = "_" ,cols_remove = FALSE)  ->
  samples.ring.RNA.df



samples.ring.RNA.df

```

### RNA
```{r}


# Load the RNA data
countData = readRDS(here("data","RNA", "repeats", "salmon", "salmon.merged.gene_counts_length_scaled.rds"))
samples.ring.RNA.df %>% column_to_rownames(var = "Sample") -> samples



m = floor(as.matrix(countData@assays@data$counts) )


dds <- DESeqDataSetFromMatrix(m,
                                colData = samples,
                                design = ~ Tissue + Location )



design(dds)
countData@assays@data$abundance %>% as.data.frame() -> abundance_df
countData@assays@data$counts %>% as.data.frame() -> count_df
```

### Remove lowly  expressed TEs
```{r}
#Consider skipping this
dds_without_filter <- dds
dds <- dds[rowSums(counts(dds)) > 10, ]


```

## Deseq
```{r}
dds <- DESeq(dds)

res <- results(dds, 
               contrast = c("Tissue", "stipe", "lamella"),
               alpha = 0.05, 
               lfcThreshold = 0.5, 
               independentFiltering = TRUE, 
               pAdjustMethod = "BH")

res.df <- as.data.frame(res[order(res$padj), ])


#res.df.all <- res.df[!is.na(res.df$padj) , ] %>%  rownames_to_column(var = "locus_tag") %>%
#  mutate(locus_tag = gsub("gene-","",locus_tag)) %>%
#  inner_join(annotation.mRNA.df) 


res.df %>%
  mutate(DE = "Significant") %>%
  mutate(DE = replace(DE, abs(log2FoldChange) <2, "Not Significant")) %>%
  mutate(DE = replace(DE, padj >0.05, "Not Significant"))  ->
  res.df.all

baseMeanPerLvl <- sapply( levels(dds$condition), function(lvl) rowMeans( counts(dds,normalized=TRUE)[,dds$condition == lvl] ) )

#Merge in the TE annotation
TE.annotation = read_csv(file = here("annotation","Repeat.classes.csv"))
TE.annotation %>%
  mutate(Name = paste0("Maror", Name)) ->
  TE.annotation

res.df.all <- res.df.all %>%
  mutate(Name = sub("-.*$", "", rownames(.)))

res.df.all <- res.df.all %>%
  left_join(TE.annotation, by = "Name")


res.df.all %>% ggplot(aes(x = log2FoldChange, y = -log10(padj), color = DE, shape = Class)) +
  geom_point(size = 2) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "red") +
  geom_vline(xintercept = c(-2, 2), linetype = "dashed", color = "red") +
  labs(title = "Volcano plot: Stipe vs Lamella",
       x = "Log2 Fold Change",
       y = "-Log10 Adjusted P-value") +
  theme_minimal() +
  scale_color_manual(values = c("Significant" = "#4472C4","Not Significant" = "grey" )) -> volcano_plot

ggsave(here("figures","Figure5","Fig5B.pdf"),
       width = 7, height = 4,plot = volcano_plot)

library(ggrepel)

res.df.all %>% 
  ggplot(aes(x = log2FoldChange, y = -log10(padj), color = DE)) +
  geom_point(size = 2) +
  # Add labels only for Significant points
  geom_text_repel(
    data = subset(res.df.all, DE == "Significant"),
    aes(label = rownames(subset(res.df.all, DE == "Significant"))),
    size = 3,
    max.overlaps = 20, # Adjust this if you have many points
    box.padding = 0.5, 
    point.padding = 0.3,
    show.legend = FALSE
  ) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "red") +
  geom_vline(xintercept = c(-2, 2), linetype = "dashed", color = "red") +
  labs(title = "Volcano plot: Stipe vs Lamella",
       x = "Log2 Fold Change",
       y = "-Log10 Adjusted P-value") +
  theme_minimal() +
  scale_color_manual(values = c("Significant" = "#4472C4","Not Significant" = "grey" )) -> volcano_plot_with_labels

ggsave(here("figures","Figure5","Fig5B_with_labels.pdf"),
       width = 7, height = 4,plot = volcano_plot_with_labels)

res.df.sig <- res.df.all[abs(res.df.all$log2FoldChange) > 2 & res.df.all$padj<0.05 , ]





```


```{r}
# Add code Markus and supplementary data.



```