---
title: "Figure 2"
output:
 html_document:
    toc: true
    toc_float: true
    code_folding: hide
    theme: flatly
date: "2024-09-11"
---

# Setup
```{r setup, include=FALSE}
# Set printing source code
knitr::opts_chunk$set(echo = TRUE)

# Load packages
# CRAN packages
library(tidyverse)
library(patchwork)
library(gridExtra)
library(rstatix)
library(purrr)
library(here)

# Bioconductor packages
library(GenomicRanges)
library(GenomicFeatures)
library(PCAtools)

# Set correct select function
select = dplyr::select

# Define tissue colors
types = c("Stipe","Lamella","Spore","control")
colors = c("#96C176FF","#CF9DDBFF","#4472C4FF","#000000FF")
types = c("Stipe","Lamella","Spore","control","stipe","lamella","spore") # Catch lowercase tissues
colors = c("#96C176FF","#CF9DDBFF","#4472C4FF","#000000FF","#96C176FF","#CF9DDBFF","#4472C4FF")
names(colors) = types

# Define genomic context colors
annotationColors = c("mRNA" = "#4472C4","TE" = "#C00000","Both" = "#9D475B","intergenic" = "#AFABAB")

# Define methylation level colors (< 0.05, 0.05 - 0.30, 0.30 - 0.75, 0.75 - 0.90, > 0.90)
methylationLevelColors = my_colors <- c(
  "Nothing"   = "#4575B4",
  "Low"  = "#91BFDB",
  "Medium"  = "#E0F3F8",
  "High"  = "#FEE090",
  "All" = "#D73027"
)

```

# Annotation

## TE reference
```{r, message=FALSE}
# Define GFF3 columns
gff3Colnames =c("seqid", "source",
                "type","start",
                "end", "score",
                "strand","phase",
                "attributes")

  # Load information about TE classes, included in repository
  TE.classes = read_csv(file = here("annotation","Repeat.classes.csv")) %>%
    rename(Name = "TEfamily") %>% 
    rename("Superfamily / Notes" = "Notes") #columns renamed for downstream use

  # Define TE file location, included in repository
  TEFile <- here("annotation","Maror2.repeatmasker.rmlib2.3.gff")

  # Read in TE dataframe from gff file
  TEdf =    read_tsv(file = TEFile, col_names = gff3Colnames,comment = "#") %>% separate(attributes, into = c("ID","target"), sep = ";") %>%
    mutate(ID = as.numeric(gsub("ID=","",ID))) %>%
    separate(target, into = c("Target","motif",
                              "motifStart","motifStop"),
             sep = " ") %>%
    mutate(motif = gsub("\"","",motif))%>%
    mutate(motif = gsub("Motif:","",motif))  %>%
    select(seqid,start,end,score,
           strand, ID,motif,
           motifStart,motifStop) %>%
    rename(ID = "TEID") %>%
    mutate(TE_ID2 = 1:n()) %>%
    mutate(motifStart = as.numeric(gsub(" ","",motifStart))) %>%
    mutate(motifStop = as.numeric(gsub(" ","",motifStop))) %>%
    dplyr::rename(TEclass = "motif") %>%
    mutate(TEclass = gsub(" ","",TEclass)) %>%
    mutate(TEclass = gsub("Maror","",TEclass)) 

 
  # Generate GRanges of TE file
  TEs = makeGRangesFromDataFrame(TEdf,
                                 seqnames.field = "seqid", 
                                 start.field = "start", 
                                 end.field = "end",
                                 strand.field = "strand",
                                 keep.extra.columns = TRUE)
  

# Merge TE classes with dataframe to add annotation and remove other repeat annotations
# From 13309 to 8893 repeats
TEdf%>%
  separate(TEclass, into = c("TEfamily","nr"), sep = "-",remove = FALSE) %>%
  inner_join(TE.classes)->
  TEdf

```

## Gene reference 
```{r, message=FALSE}

gtfFile = here("annotation","GCF_018924745.1_UU_Maror_2_genomic.gff")	# Included in repository
txdb <- makeTxDbFromGFF(file=gtfFile, dataSource="ensemblgenomes",format = "gff3")

# define GFF3 columns
gff3Colnames =c("seqid", "source",
                "type","start",
                "end", "score",
                "strand","phase",
                "attributes")
  # Read in the gff file
  annotation.df =    read_tsv(file = gtfFile, col_names = gff3Colnames,comment = "#") 

# Keep only mRNA annotations
 annotation.df %>% filter(type =="mRNA") %>%
   group_by(seqid,start,end, strand) %>%
   slice_head(n = 1) %>% # Remove multiple mRNA annotations on the same genomic region
   ungroup() %>%
   separate_longer_delim(attributes, delim = ";") ->
   test
  # Keep only relevant attributes and give them separate columns
  # Drop any unused columns
  test %>% select(seqid,start,end,strand,attributes) %>%
   separate(attributes, into = c("key","value"), sep = "=") %>%
   filter(key %in% c("Name","locus_tag","product")) %>%
   pivot_wider(values_from = "value",names_from = "key") -> 
   annotation.mRNA.df

# Add tx_id column
annotation.mRNA.df %>% select(seqid,start,end, strand,Name,locus_tag,product) %>%
  mutate(tx_id = 1:n()) -> 
  annotation.mRNA.df

# Create GRanges object
mRNAs = makeGRangesFromDataFrame(annotation.mRNA.df,
                                 seqnames.field = "seqid", 
                                 start.field = "start", 
                                 end.field = "end",
                                 strand.field = "strand",
                                 keep.extra.columns = TRUE)
  

```

## Relationship between XM and XP IDs
```{r, inlcude false  }
# Add XM and XP IDs
gene2ProteinFile = here("annotation","gene2protein_relationship.csv")

relationship_df = read_csv(gene2ProteinFile)

relationship_df %>% mutate(Name = XM_ID) -> relationship_df
annotation.mRNA.df = inner_join(annotation.mRNA.df,relationship_df , by = "Name")
```

# Samples 
```{r, message=FALSE}

# Read and organize sample data
samples.ring.methyl.df = read_csv(file = here("data","meDNA","meDNA.metaData.csv"))

samples.ring.methyl.df %>% arrange(Tissue,Location,Replicate) -> 
  samples.ring.methyl.df

```

# Read in data
```{r, message=FALSE}
#TODO: Insert DOI
# Data can be obtained from ###INSERT DOI#####
meData_path <- here("data", "meDNA", "methylationData.samples.QC.csv.gz")

# Read in the data, read_csv automatically handles the decompression
# Data consists of every position of every sample that is considered in the final dataset. 
methylationData.3.QC <- read_csv(meData_path)

```

# Figure 1D

```{r, message=FALSE}
# Calculate methylated fraction per sample per tissue

methylationData.3.QC %>%
  mutate(methylated = depth*percent /100) %>%
  mutate(notMethylated = depth - methylated) %>%
  group_by(Sample) %>%
  summarise(methylated = sum(methylated), notMethylated = sum(notMethylated)) %>%
  mutate(fraction = methylated /(notMethylated+methylated))->
  sum

sum %>%
  inner_join(samples.ring.methyl.df) -> sum_wide

sum_wide %>%
  ggplot(aes(x = Tissue, y = fraction,fill = Tissue,)) +
  geom_boxplot(outliers = FALSE)+
  geom_jitter(width = 0.1,mapping = aes(shape =Location)) + 
  theme_light()+
  scale_fill_manual(values = colors) ->
  fig1D

ggsave(here("figures","Figure1","fig1D.pdf"),
       plot = fig1D,
        width = 4, height = 5, units = "in", dpi = 300)

# Perform significance testing for figure 1D
# Test variance
levene_test(fraction ~ Tissue, data = sum_wide) # p>0.05 so we assume homogeneity of Variance

# Perform ANOVA and test for normality 
model <- aov(fraction ~ Tissue, data = sum_wide)
res <- residuals(model)
shapiro.test(res) # p<0.05 so no normality. Perform non-parametric test instead

# Non-parametric test
kruskal.test(fraction ~ Tissue, data = sum_wide) # p < 0.001
# post-hoc dunns test
dunn_res <- sum_wide %>%
  dunn_test(fraction ~ Tissue, p.adjust.method = "BH")
write.csv(dunn_res, here("results", "meDNA", "fig1D_significance_test.csv"))
```


# Figure2 A + C

```{r, message=FALSE}

# Group data by:
# location (Gene body, TE, intergenic)
# Tissue (Lamella, Spore, Stipe)
# Location (W, NW, N, NE)
# Replicate (1, 2, 3)
# Calculate the positions considered, mean read depth and mean methylation percentage
methylationData.3.QC %>% 
  group_by(location,Tissue,Location,Replicate2) %>% 
  summarise(n = n(), depth = mean(depth), methylation = mean(percent)) ->
  methylationData.3.QC.annotation.distribution

# Plot Figure 2A
methylationData.3.QC.annotation.distribution %>%
  select(Tissue,Location,Replicate2,methylation,location) %>% # Select relevant variables
  mutate(IDsample = paste(Location,Replicate2,Tissue,sep = "_")) %>% # Create sample identifier
  mutate(fraction = methylation /100)%>% # Convert methylation to fraction
  ggplot(aes(x = location, y = fraction, fill = location)) + 
  geom_boxplot(outliers = FALSE) +
  geom_jitter(width = 0.2) + 
  theme_light() +
  ylim(c(0,1))+
  scale_fill_manual(values = colors)  -> fig2A

ggsave(here("figures","Figure2","fig2A.pdf"),
       plot = fig2A,
        width = 4, height = 5, units = "in", dpi = 300)

# Plot Figure 2C
methylationData.3.QC.annotation.distribution %>%
  select(Tissue,Location,Replicate2,methylation,location) %>% # Select relevant variables
  mutate(IDsample = paste(Location,Replicate2,Tissue,sep = "_")) %>% # Create sample identifier
  mutate(fraction = methylation /100)%>% #Convert methylation to fraction
  ggplot(aes(x = Tissue, y = fraction, fill = Tissue)) + 
  geom_boxplot(outliers = FALSE) +
  geom_jitter(width = 0.2) + 
  theme_light() +
  scale_fill_manual(values = colors) +
  facet_wrap(.~location, scales = "free_y") -> fig2C

ggsave(here("figures","Figure2","fig2C.pdf"),
            plot = fig2C,width = 8, height = 5, units = "in", dpi = 300)


```

# Figure 2B

```{r, message=FALSE}

# Select outliers from the data
methylationData.3.QC.annotation.distribution %>% 
  select(Tissue,Location,Replicate2,methylation,location) %>%
  mutate(IDsample = paste(Location,Replicate2,Tissue,sep = "_")) %>%
  filter(IDsample %in%
           c("northeast_1_stipe","north_3_stipe","north_3_spore")) %>%
    mutate(fraction = methylation /100) %>%
    select(-methylation) %>%
    pivot_wider(values_from = "fraction", names_from = "location" ) -> outliers  
  
# Plot figure 2
  methylationData.3.QC.annotation.distribution %>% 
    select(Tissue,Location,Replicate2,methylation,location) %>%
      mutate(IDsample = paste(Location,Replicate2,Tissue,sep = "_")) %>%
    mutate(fraction = methylation /100) %>%
    select(-methylation) %>%
    pivot_wider(values_from = "fraction", names_from = "location" )  %>%
    ggplot(aes(x = GeneBody, y = TE, color = Tissue)) + geom_point()+
    theme_light()+
    geom_text_repel(data = outliers,aes(label = IDsample), color = "black")  +
    scale_color_manual(values = colors) -> 
    fig2B

ggsave(here("figures","Figure2","fig2B.pdf"),plot = fig2B,
       width = 6, height = 5, units = "in", dpi = 300)

```

# Statistical tests for figure 2C

```{r, message=FALSE}

# Perform a kruskal-wallis test on the different tissues per genomic context
methylationData.3.QC.annotation.distribution %>% 
    select(Tissue,Location,Replicate2,methylation,location) %>%
      mutate(IDsample = paste(Location,Replicate2,Tissue,sep = "_")) %>%
    mutate(fraction = methylation /100) %>%
  group_by(location) %>%
  summarise(
    p_value = tryCatch({
      kruskal.test(fraction ~ Tissue, data = cur_data())$p.value
    }, error = function(e) NA),
  )%>% 
  mutate(comparison = "Location") %>%
  mutate(adj_pvalue = p.adjust(p_value, method = "BH")) %>%
  mutate(significant = "No") %>%
  mutate(significant = replace(significant, adj_pvalue < (0.05), "Yes")) ->
  kruskal_results.Methylation



results <- methylationData.3.QC.annotation.distribution %>% 
  select(Tissue, Location, Replicate2, methylation, location) %>%
  mutate(
    IDsample = paste(Location, Replicate2, Tissue, sep = "_"),
    fraction = methylation / 100
  ) %>%
  group_by(location) %>%
  group_modify(~{
    
    df <- .x  # current location
    
    ## --- Kruskal–Wallis test ---
    kw <- tryCatch(
      kruskal.test(fraction ~ Tissue, data = df),
      error = function(e) NULL
    )
    
    kw_p <- if (!is.null(kw)) kw$p.value else NA
    
    ## --- Dunn test (pairwise comparisons) ---
    dunn <- df %>%
      dunn_test(fraction ~ Tissue, p.adjust.method = "BH") %>%
      mutate(
        kw_p_value = kw_p
      )
    
    dunn
  }) %>%
  ungroup() %>%
  
  ## Adjust the Kw p-values across all locations
  group_by(location) %>%
  mutate(
    kw_p_adj = p.adjust(unique(kw_p_value), method = "BH")
  ) %>%
  ungroup() %>%
  
  ## Add significance flags
  mutate(
    kw_significant = kw_p_adj < 0.05,
    pairwise_significant = p.adj < 0.05
  )

write_csv(results, here("results","meDNA","fig2C_significance_test.csv"))

```




```{r, message=FALSE}
# Exploratory plotting of methylation level of different contexts
# Not included in final results
methylationData.3.QC %>% 
  group_by(Tissue, location) %>%
  summarise(mean = mean(percent))


methylationData.3.QC %>% 
  mutate(methylationLevel = "High") %>%
  mutate(methylationLevel = replace(methylationLevel,
                                    percent <90,
                                    "Average" )) %>%
  mutate(methylationLevel = replace(methylationLevel,
                                    percent <10,
                                    "Low" )) ->
  methylationData.3.QC

methylationData.3.QC %>% 
  group_by(Location,location, Tissue,methylationLevel) %>%
  summarise(n = n()) -> methylationData.3.QC.summary

methylationData.3.QC.summary %>%
  group_by(Location,location, Tissue) %>%
  summarise(Total = sum(n)) %>% 
  inner_join(methylationData.3.QC.summary) %>%
  mutate(fraction = n /Total) -> methylationData.3.QC.summary

methylationData.3.QC <- methylationData.3.QC %>%
  mutate(methylationLevel = factor(methylationLevel, levels = c("High", "Average", "Low")))

ggplot(methylationData.3.QC, aes(x = Tissue, fill = methylationLevel)) +
  geom_bar(position = "fill") +
  facet_wrap(facets = vars(location)) + # Ensure 'location' is used properly
  scale_fill_manual(values = c("Low" = "blue", "Average" = "grey", "High" = "red")) +
  theme_minimal() +
  labs(
    fill = "Methylation Level", 
    x = "Tissue", 
    y = "Count"
  )-> methylationDistribution
ggsave(here("figures","Figure2","MethylationDistribution.pdf"),plot = methylationDistribution)
```





